In [1]:
import numpy as np
import pandas as pd
import os
import csv
import re
from pdfminer import high_level
import nltk
from nltk.tokenize import word_tokenize
nltk. download("punkt")

[nltk_data] Downloading package punkt to /home/samanvitha/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [2]:
#Function to extract Phone Numbers from string using regular expressions
def extract_phone_numbers(string):
    r = re.compile(r'(\d{3}[-\.\s]??\d{3}[-\.\s]??\d{4}|\(\d{3}\)\s*\d{3}[-\.\s]??\d{4}|\d{3}[-\.\s]??\d{4})')
    phone_numbers = r.findall(string)
    #return [re.sub(r'\D', '', number) for number in phone_numbers]
    
    numbers = [re.sub(r'\D', '', number) for number in phone_numbers]
    for item in numbers:
        if len(item) == 10 or len(item) == 14:
            return item

In [3]:
def extract_email_addresses(string):
#     r = re.compile(r'[\w\.-]+@[\w\.-]+')
    r = re.compiler(^[a-zA-Z0-9+_.-]+@[a-zA-Z0-9.-]+$)  
    return r.findall(string)

In [4]:
with open('techskill.csv', newline='') as csvfile:
        data = list(csv.reader(csvfile))
        
def extract_skills(extracted_text):
    skills = []
   
    a_list = nltk. word_tokenize(extracted_text.lower()) #Split text into list of words.
    for item in data:
        for sub_item in item:
            if sub_item in a_list:
                skills.append(sub_item)
    return skills

In [6]:

d = 'Resumes'
cols = ["name","phone_number","email","skills"]
rows = []
def select_files_in_folder(d, ext):
    for file in os.listdir(d):
        if file.endswith('.%s' % ext):
            yield os.path.join(d, file)


for file in select_files_in_folder(d, 'pdf'):
    pages = [0,1] # just the first page
    extracted_text = high_level.extract_text(file, "", pages)
    #name = extract_names(extracted_text)
    name = file[8:(len(file))-4]
    phone_number = extract_phone_numbers(extracted_text)
    email = extract_email_addresses(extracted_text)
    skills = extract_skills(extracted_text)
    rows.append({'name': name,
                     'phone_number':phone_number,
                        'email':email,
                         'skills':skills})
out_df = pd.DataFrame(rows, columns = cols)

In [7]:
print(out_df)

                                                 name phone_number  \
0                                 Abhijay Kumar Singh   7760380991
1                Apoorva_R_Resume - Apoorva Bharadwaj   7204441749
2                      HEMANTH_Resume - Hemanth Kumar   8553290086
3                                           Koushik J   7349713094
4                                        Sahana Gowda   8296650819
5           Amogha_Subramanya - Amogha Subramanya D A   8553511856
6                              newresume - Hiba Iqbal   9731618840
7                                        Akshay Anand   9431913301
8   Divya_Madhav_Kamath_Resume_April42018 - Divya ...   9591721577
9                                          Nandan K R   9480233978
10                                Gaurav Gobind Singh         None
11                 Anoop_Bhat_N_Resume - Anoop bhat n   9900831736
12                                    Madgula Mahathi   7981392446
13                                      Sumangala Rao   9191645227
14                                    Manasa Kanathur   9902206706
15                               SRM_ML - Sourabh R M   9880125575
16                                       Sushil Kumar   9631713085
17                       Resume_july - Rakesh gourani   9164260924
18                         praveen-resume - Praveen G   9743175960
19                                            Medha K   8749037897
20                                 Harsha - Harsha Bm   9174119699
21                                           Ahalya R   8971774677
22                                    Siddhant Sharma   9742572913
23                                       Rutwik Nayak   9964442953
24                           PradeepPai - Pradeep Pai   8971743181
25                                    Shaheed Nehal A   7406740089
26                          updatedCV - sandesh hegde   9196635857
27                                 Kanakam Sai Dimple   8867419797
28                                           Aarthi T   8762068961
29                                Arunima Rashmi Giri   8971636350
30                                       Amogh Mahesh   8050203235
31              Abhishek_Bisht - Abhishek Singh Bisht   9738959449
32                                         Vijeth V K   9731362817
33                           Nikhil Prabhakar Kottary   9187489821
34                     WD resume - ashwin bhadravathi   8892369197
35                                    Ashritha Shetty   9191081432
36                     Resume2.3 - Niveditha Somayaji   9901476977
37                        Docs_Resume1.3 - Spoorthi M   7795912621
38                                     AJAYB - AJAY B   8904636160
39                                         T S Kushal   9449938598
40                                       Aravinda S V   9901960855
41                                  K V Sampritha Rao   9148180450
42                                     Shripriya Bhat   9591682304
43                                       Samanvitha_S   8904868690
44                                       Shwet Sharma   9482026516
45                                   Meghana A Rajeev   9481325094
46                Yogeesh Rajendra Resume - YOGEESH R   9480560233

                              email  \
0           [abhijayks98@gmail.com]
1    [apoorvabharadwaj02@gmail.com]
2           [hemanthkm05@gmail.com]
3          [koushikj9823@gmail.com]
4        [sahanagowda146@gmail.com]
5    [amoghasubramanya17@gmail.com]
6          [hibaiqbal781@gmail.com]
7      [akshayanand.2808@gmail.com]
8     [divyamadhavkamath@gmail.com]
9            [nandankr74@gmail.com]
10                               []
11           [anoopnbhat@gmail.com]
12       [madgulamahathi@gmail.com]
13        [sumangala3rao@gmail.com]
14       [manasakanathur@gmail.com]
15        [sourabhraja97@gmail.com]
16         [sushilsoni39@gmail.com]
17    [rakeshgourani1740@gmail.com]
18         [praveen.g126@gmail.com]
19         [medhakalkura@gmail.com]
20         [bmharsha18jc@gmail.com]
21           [ahalya.r22@gmail.com]
22     [siddhantsharma97@gmail.com]
23         [rutwik.nayak@gmail.com]
24        [paipradeep512@gmail.com]
25         [shahidnehala@gmail.com]
26        [sandeshhegde9@gmail.com]
27          [dimple.1698@gmail.com]
28          [aarthi.t.29@gmail.com]
29        [arunimagiri13@gmail.com]
30             [amoghm14@gmail.com]
31     [abhisinghbisht04@gmail.com]
32           [vijethvk11@gmail.com]
33     [nikhil.p.kottary@gmail.com]
34         [ashwinsjce97@gmail.com]
35     [ashrithashetty27@gmail.com]
36   [nivedithansomayaji@gmail.com]
37         [spoorthi2112@gmail.com]
38         [balajiajay97@gmail.com]
39       [t.s.kushal9919@gmail.com]
40              [aravisv@gmail.com]
41        [sampritharao5@gmail.com]
42        [bhatshripriya@gmail.com]
43  [samanvitha.sateesha@gmail.com]
44     [shwet.condinya96@gmail.com]
45      [meghana.arakkal@gmail.com]
46        [yogeesh.srkvs@gmail.com]

                                               skills
0              [mysql, anaconda, python, python, c++]
1   [algorithms, cryptography, mysql, tensorflow, ...
2       [threading, mysql, python, python, parser, c]
3   [mysql, python, jupyter, python, javascript, p...
4   [algorithms, mysql, dataset, python, python, m...
5   [algorithms, mysql, anaconda, python, spyder, ...
6   [flower, queries, dataset, visual, python, pyt...
7   [algorithms, pandas, seaborn, mysql, python, k...
8   [algorithms, mysql, keras, python, pillow, nlt...
9     [mysql, keras, ansible, python, python, css, c]
10                                                 []
11  [dataset, python, spark, xgboost, python, fram...
12  [mysql, dataset, python, django, python, djang...
13  [opencv, open, python, curses, python, open, m...
14  [algorithms, mysql, postgresql, python, python...
15  [matplotlib, mysql, postgresql, keras, tensorf...
16          [mysql, python, python, php, c++, css, c]
17  [algorithms, opencv, python, logging, python, ...
18  [tensorflow, python, interactive, python, c++, c]
19                   [opencv, python, python, c++, c]
20                [mysql, dataset, python, python, c]
21          [mysql, python, python, php, c++, css, c]
22  [flower, keras, python, django, python, framew...
23  [mysql, tensorflow, anaconda, python, spyder, ...
24  [algorithms, open, dataset, python, python, op...
25  [algorithms, try, python, django, python, djan...
26   [algorithms, dataset, python, python, github, c]
27  [algorithms, open, mysql, keras, python, kivy,...
28  [algorithms, mysql, python, python, github, c+...
29  [libraries, libraries, pandas, seaborn, python...
30  [algorithms, opencv, mysql, keras, tensorflow,...
31  [python, tkinter, pattern, python, github, jav...
32  [supervisor, anaconda, python, spyder, jupyter...
33  [opencv, mysql, keras, anaconda, python, spyde...
34  [threading, dataset, python, interactive, pyth...
35  [mysql, dataset, python, python, php, c++, css...
36       [mysql, visual, python, python, c++, css, c]
37  [mysql, dataset, anaconda, python, spyder, jup...
38  [mysql, dataset, keras, tensorflow, anaconda, ...
39               [mysql, python, python, php, c++, c]
40  [mysql, python, spyder, jupyter, python, php, ...
41            [mysql, visual, wifi, php, c++, css, c]
42  [mysql, money, python, python, github, javascr...
43  [mysql, python, python, github, javascript, c+...
44                          [mysql, php, c++, css, c]
45  [opencv, open, mysql, tensorflow, python, spyd...
46        [click, try, merchant, plan, shell, matlab]

In [ ]:
out_df.to_excel('big_data_df.xlsx')